name: Build macOS App

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install py2app
        run: pip3 install py2app

      - name: Build .app
        run: python3 setup.py py2app

      - name: Zip the .app (чтобы сохранить права и структуру)
        run: |
          cd dist
          zip -r "AppLauncher.zip" "App Launcher.app"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppLauncher-mac
          path: dist/AppLauncher.zip
